FROM php:7.4-apache
COPY .  /var/www/html/
ENV APACHE_DOCUMENT_ROOT /var/www/html/public/
COPY default.conf /etc/apache2/sites-enabled/000-default.conf
WORKDIR /var/www/html/public/

RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
EXPOSE 80



//

docker run -i --rm -p 80:80 --name manu --mount type=bind,source=C:\web\htdocs\MyScripts\manufacture-docs,target=/var/www/ manu-docs
